GET http://localhost:5000/api/orders/6aa6e704d3a3ad483bae659e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYTZkOGNjOWNlZWJjZTA2MGIxMmE1NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzg5MzIzMTQ1LCJleHAiOjE3ODk5Mjc5NDV9.tho4pULiYQvUcpn8ey0dizjDDVIrZoAqUhdlxPKmLM4